global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'postgresexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.17.0.2:9187']

#alerting:
 # alertmanagers:
  #- scheme: http
   # static_configs:
    #- targets: 
     # - 'alertmanager:9093'

